# Generated by Django 4.1.7 on 2023-03-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Data1', models.CharField(max_length=50)),
                ('Data2', models.CharField(max_length=50)),
            ],
        ),
    ]
