# Generated by Django 4.1.7 on 2023-03-15 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='Data1',
            new_name='data1',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='Data2',
            new_name='data2',
        ),
    ]
