# Generated by Django 4.1.7 on 2023-03-15 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_data1_entry_data1_rename_data2_entry_data2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='data1',
            new_name='Data1',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='data2',
            new_name='Data2',
        ),
    ]
